### ISSUE TITLE
Vienna is not in Italy

### ISSUE THREAD

**Issue by lukalt** [denniskupec/csgo-matchmaking-ip-ranges#2]
Hello,

as the title says, Vienna is the capital of Austria, not in Italy. I don't want to open a new pull request for this simple change.

Thank yoy

**Comment by ghost** [comment]
I don't think it's trying to say Vienna is in Italy. Those are just example locations of the areas those servers are serving. For example EU North is in Stockholm (Sweden) and it serves Nordic countries and Russia. And in this case, most Italians will connect to EU East and so on.
