### ISSUE TITLE
EU West - 146.66.153.0/24

### ISSUE THREAD

**Issue by realnc** [denniskupec/csgo-matchmaking-ip-ranges#8]
www.geoip.co.uk says it's in Switzerland.

hostname: Valve CS:GO EU West Server (srcds076.132.3)
version : 1.35.3.1 secure
udp/ip  : 146.66.153.0:27017
os      :  Linux
type    :  official dedicated

**Comment by realnc** [comment]
Are you not updating the list anymore?

**Comment by denniskupec** [comment]
I update the list with what I can. Reverse DNS and ipinfo.io shows Luxembourg.

**Comment by realnc** [comment]
Perhaps geoip is wrong, but the IP is valid.

**Comment by denniskupec** [comment]
IP is valid, yes.

**Comment by realnc** [comment]
But it's not in your list. That's why I asked whether you're still updating it or not :-P
